def bytes_to_ptr(*args, **kwargs): ...
def numpy_contiguous_to_ptr(*args, **kwargs): ...
def numpy_to_ptr(*args, **kwargs): ...
def ptr_to_bytes(*args, **kwargs): ...
def ptr_to_numpy(*args, **kwargs): ...
def start_thread(*args, **kwargs): ...
def stop_thread(*args, **kwargs): ...
